apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
  name: nginx
spec:
  rules:
  - host: test.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-emoji-svc
            port:
              number: 80
      - path: /happy
        pathType: Prefix
        backend:
          service:
            name: nginx-happy-svc
            port:
              number: 80
      - path: /sad
        pathType: Prefix
        backend:
          service:
            name: nginx-sad-svc
            port:
              number: 80
