apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
          #nginx.ingress.kubernetes.io/rewrite-target: /
  name: nginx
spec:
  rules:
  - host: test.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-i-svc
            port:
              number: 80
      - path: /am
        pathType: Prefix
        backend:
          service:
            name: nginx-am-svc
            port:
              number: 80
